export const DOCUMENTO_SUGESTOES = [
  'RG',
  'CPF',
  'CNH',
  'Título de eleitor',
  'Certificado de reservista',
  'Diploma',
  'Declaração de conclusão',
  'Histórico acadêmico',
  'Currículo Lattes',
  'Currículo Vitae',
  'Carta de intenção',
  'Carta de recomendação',
  'Projeto de pesquisa',
  'Pré-projeto',
  'Comprovante de residência',
  'Comprovante de pagamento',
  'Comprovante de inscrição',
  'Certidão de nascimento',
  'Certidão de casamento',
  'Foto 3x4',
  'Certificados de cursos',
  'Comprovante de experiência profissional',
  'Declaração de vínculo',
  'Autodeclaração',
  'Laudo médico',
  'Outro',
] as const

export type DocumentoSugestao = typeof DOCUMENTO_SUGESTOES[number]